### ISSUE TITLE
IOError: flankingRead.unPaired.info doesn't exist

### ISSUE THREAD

**Issue by reubwn** [JinfengChen/RelocaTE2#15]
Hello,

Firstly thanks for making this program - it is very useful.

I am running RelocaTE2 on some draft genome sequences and receiving quite a few IOErrors in the logfile. The problem is due to certain "[scaffoldname].flankingRead.unPaired.info" files not existing:

```
fullread bam: /foo/bar/results/repeat/bwa_aln/scaffolds_final.AK11.repeat.fullreads.bwa.sorted.bam
junction fullread number: 0
Traceback (most recent call last):
  File "/foo/bar/miniconda3/envs/RelocaTE2/bin/relocaTE_insertionFinder.py", line 1825, in <module>
    main()
  File "/foo/bar/miniconda3/envs/RelocaTE2/bin/relocaTE_insertionFinder.py", line 1814, in main
    read_unpaired_read_info(unpaired_read_info, teReadsInfo)
  File "/foo/bar/miniconda3/envs/RelocaTE2/bin/relocaTE_insertionFinder.py", line 1705, in read_unpaired_read_info
    with open (unpaired_read_info, 'r') as filehd:
IOError: [Errno 2] No such file or directory: '/foo/bar/results/repeat/flanking_seq/AK1105993.flankingReads.unPaired.info'
```

Could you explain this error message a bit more? I assume it must occur at putative insertion sites that do not have any reads mapped upstream / downstream? For example, on a short scaffold where the 'flanking' region simply doesn't exist. I wonder then if this is really an error, or just an unsupported insertion site that should be filtered out.

Any help on the subject would be greatly appreciated. Cheers!

**Comment by emoranska** [comment]
Hi @JinfengChen,
I have the same problem as @reubwn. I try to run RelocaTE2 for the sugar beet reference genome and sample data derived from the genome sequencing project for checking parameters before running my samples.

The part of my log file and the error message I've received looks like that:
```
find insertions on contig129940
find insertions on contig129947
fullread bam: /home/emoranska/miniconda3/envs/RelocaTE2/refbeet_test_2/RefBeet_SRR868890_MITEtest_RelocaTE2_outdir/repeat/bwa_aln/Beta_vulgaris.RefBeet-1.2.2.dna.toplevel.repeat.fullreads.bwa.sorted.bam
junction fullread number: 0
Traceback (most recent call last):
  File "/home/emoranska/miniconda3/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1825, in <module>
    main()
  File "/home/emoranska/miniconda3/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1814, in main
    read_unpaired_read_info(unpaired_read_info, teReadsInfo) 
  File "/home/emoranska/miniconda3/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1705, in read_unpaired_read_info
    with open (unpaired_read_info, 'r') as filehd:
IOError: [Errno 2] No such file or directory: '/home/emoranska/miniconda3/envs/RelocaTE2/refbeet_test_2/RefBeet_SRR868890_MITEtest_RelocaTE2_outdir/repeat/flanking_seq/contig145049.flankingReads.unPaired.info'
fullread bam: /home/emoranska/miniconda3/envs/RelocaTE2/refbeet_test_2/RefBeet_SRR868890_MITEtest_RelocaTE2_outdir/repeat/bwa_aln/Beta_vulgaris.RefBeet-1.2.2.dna.toplevel.repeat.fullreads.bwa.sorted.bam
junction fullread number: 0
Traceback (most recent call last):
  File "/home/emoranska/miniconda3/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1825, in <module>
    main()
  File "/home/emoranska/miniconda3/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1814, in main
    read_unpaired_read_info(unpaired_read_info, teReadsInfo) 
  File "/home/emoranska/miniconda3/envs/RelocaTE2/scripts/relocaTE_insertionFinder.py", line 1705, in read_unpaired_read_info
    with open (unpaired_read_info, 'r') as filehd:
IOError: [Errno 2] No such file or directory: '/home/emoranska/miniconda3/envs/RelocaTE2/refbeet_test_2/RefBeet_SRR868890_MITEtest_RelocaTE2_outdir/repeat/flanking_seq/contig107098.flankingReads.unPaired.info'
```

The same error occurs for all finding insertions. Any ideas on how to solve it?
Thanks a lot!

**Comment by TobyBaril** [comment]
Hi,
I am also experiencing the same errors. Was there any resolution to this?
